add Vouched rule
auth0/rules pull request #240
Opened 2020-08-31 22:26 UTC by marcusoliver

### Description
Add the Vouched rule to be used a template. 
The rule redirects users to Vouched to complete the identity verification process. When Vouched redirects back via the continue url, the rule saves the result to app metadata. If result already exists in the app metadata, the user is not redirected to Vouched. The rule also determines if the user is allowed to proceed (successfully) through the authentication flow based on the result.

2020-09-01 03:44 UTC, joshcanhelp commented on src/rules/vouched-verification.js
> + * **ID Verification Process**
TODO: Pull in the description from Marketplace and link to the installation guide.

2020-09-01 15:35 UTC, seejee submitted a review, later dismissed

2020-09-01 21:18 UTC, joshcanhelp commented
@marcusoliver - Thanks for this, it's looking great! Nothing jumps out at me so I'm going to pass this along to our Security group for review.

2020-09-02 18:30 UTC, joshcanhelp commented
@marcusoliver - One more thing to note ... our [Rule utility library](https://www.npmjs.com/package/@auth0/rule-utilities) will be available for use tomorrow in production. [You can see an example of how it's used here](https://github.com/auth0/rule-utilities/blob/master/examples/redirectRuleExample.js). There won't be any large changes you'll need to make, just a few to enable some extra checks. When that's ready to include, I'll submit another review calling out the handful of changes to make.

2020-09-02 21:59 UTC, marcusoliver commented
Sounds good! Thanks for all your help.

2020-09-03 19:03 UTC, joshcanhelp requested changes
Alright, the [Rule utility library](https://github.com/auth0/rule-utilities) is ready for use. I left suggestions here, if that helps. After that, I think we're ready to merge this 👍

2020-09-03 19:03 UTC, joshcanhelp commented on src/rules/vouched-verification.js
> +    const defaultUiUrl = 'https://console.vouched.id';
```suggestion
    const defaultUiUrl = 'https://console.vouched.id';
    const idTokenClaim = 'https://vouched.id/is_verified';
```

2020-09-03 19:03 UTC, joshcanhelp commented on src/rules/vouched-verification.js
> +                        context.idToken['https://vouched.id/is_verified'] = false;
```suggestion
                        context.idToken[idTokenClaim] = false;
```

2020-09-03 19:03 UTC, joshcanhelp commented on src/rules/vouched-verification.js
> +        context.idToken['https://vouched.id/is_verified'] = true;
```suggestion
        context.idToken[idTokenClaim] = true;
```

2020-09-03 19:50 UTC, marcusoliver commented
@joshcanhelp i merged your suggestions. that was helpful!
you mentioned previously about adding the integration guide to the header block. is this needed before merging or can it be a subsequent PR?

2020-09-04 17:18 UTC, joshcanhelp commented
@marcusoliver - Sorry, I thought I responded here ... we can add it in a later PR 👍  we'll want to standardize how we do that on our end so it will probably be something we can handle for you.

2020-09-04 17:20 UTC, joshcanhelp approved these changes
🎉

2020-09-08 14:23 UTC, joshcanhelp commented on src/rules/vouched-verification.js
> +                                                configuration.VOUCHED_CONTINUE_URL,
```suggestion
                                                configuration.VOUCHED_CONTINUE_URL,
                                                `https://${context.request.hostname}/continue`
```

2020-09-08 20:33 UTC, joshcanhelp commented on src/rules/vouched-verification.js
> +                                                `https://${context.request.hostname}/continue`
```suggestion
                                                `https://${context.request.hostname}/continue`,
```

2020-09-08 20:33 UTC, joshcanhelp commented on src/rules/vouched-verification.js
> +                                                `https://${context.request.hostname}/continue`
```suggestion
                                                `https://${context.request.hostname}/continue`,
```

2020-09-11 17:56 UTC, joshcanhelp approved these changes

2020-09-11 20:25 UTC, merged